### ISSUE TITLE
[Translation Support] How to join Wuhan2020

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#164]
Need to add all language support for the following document:
[blog/zh-cn/how-to-join-wuhan2020.md](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/blog/zh-cn/how-to-join-wuhan2020.md)

- [x] To English: `blog/en-us/how-to-join-wuhan2020.md`
- [ ] To Japanese: `blog/ja-jp/how-to-join-wuhan2020.md`
- [x] To Italiana: `blog/it-it/how-to-join-wuhan2020.md`
- [x] To French: `blog/fr-fr/how-to-join-wuhan2020.md`: In progress @gakki88

**Comment by GindaChen** [comment]
@iLtc

**Comment by iLtc** [comment]
#166 is the English version

**Comment by chenrui333** [comment]
@jeremy0519 @AnnaCICI @gakki88 Please take a peek on the French item.

**Comment by gakki88** [comment]
I'm on the french translation, just saying to avoid overlap

**Comment by jeremy0519** [comment]
Maybe i will do the it-it one. But i am a little busy these days.

**Comment by jeremy0519** [comment]
I will do as soon as i am free.

**Comment by jeremy0519** [comment]
I'm now on the it-it translation

**Comment by jeremy0519** [comment]
Need to add all language support for the following document:
blog/zh-cn/how-to-join-wuhan2020.md

- [x]  To English: blog/en-us/how-to-join-wuhan2020.md
- [ ]  To Japanese: blog/ja-jp/how-to-join-wuhan2020.md
- [x]  To Italiana: blog/it-it/how-to-join-wuhan2020.md
- [ ]  To French: blog/fr-fr/how-to-join-wuhan2020.md: In progress @gakki88

**Comment by jeremy0519** [comment]
@GindaChen You may remove the kind/question label.

**Comment by lovepoem** [comment]
暂时关闭
