### ISSUE TITLE
[Translation Support] Collaborative process publishing

### ISSUE THREAD

**Issue by jeremy0519** [wuhan2020/wuhan2020.github.io#306]
Need to add all language support for the following document:
[blog/zh-cn/collaborative-process-publishing.md](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/blog/zh-cn/collaborative-process-publishing.md)

 

- [ ] To English: `blog/en-us/collaborative-process-publishing.md`
- [ ] To Japanese: `blog/ja-jp/collaborative-process-publishing.md`
- [ ] To Italiana: `blog/it-it/collaborative-process-publishing.md`
- [ ] To French: `blog/fr-fr/collaborative-process-publishing.md`
- [ ] To Portugues: `blog/pt-br/collaborative-process-publishing.md`
