### ISSUE TITLE
[Translation Support] Nav project introduced

### ISSUE THREAD

**Issue by jeremy0519** [wuhan2020/wuhan2020.github.io#307]
Need to add all language support for the following document:
[blog/zh-cn/nav-project-introduced.md](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/blog/zh-cn/nav-project-introduced.md)

- [ ] To English: `blog/en-us/nav-project-introduced.md`
- [ ] To Japanese: `blog/ja-jp/nav-project-introduced.md`
- [ ] To Italiana: `blog/it-it/nav-project-introduced.md`
- [ ] To French: `blog/fr-fr/nav-project-introduced.md`
- [ ] To Portugues: `blog/pt-br/nav-project-introduced.md`

**Comment by lovepoem** [comment]
Blog的翻译应该向后放放，优先级更高的应该是docs下的文章

**Comment by lovepoem** [comment]
@jeremy0519 你在slack上找我下

**Comment by jeremy0519** [comment]
你可以把priority设成低的

**Comment by jeremy0519** [comment]
> Blog的翻译应该向后放放，优先级更高的应该是docs下的文章

你可以把priority设成低的

**Comment by jeremy0519** [comment]
> Blog的翻译应该向后放放，优先级更高的应该是docs下的文章
