### ISSUE TITLE
[Translation Support] Need questionnaire

### ISSUE THREAD

**Issue by jeremy0519** [wuhan2020/wuhan2020.github.io#308]
Need to add all language support for the following document:
[blog/zh-cn/need-questionnaire.md](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/blog/zh-cn/need-questionnaire.md)

- [x] To English: `blog/en-us/need-questionnaire.md`
- [ ] To Japanese: `blog/ja-jp/need-questionnaire.md`
- [ ] To Italiana: `blog/it-it/need-questionnaire.md`
- [ ] To French: `blog/fr-fr/need-questionnaire.md`
- [ ] To Portugues: `blog/pt-br/need-questionnaire.md`

**Comment by ashfaq92** [comment]
[survey translated.docx](https://github.com/wuhan2020/wuhan2020.github.io/files/4270113/survey.translated.docx)
translated in english.
now you can translate this into other languages easily

**Comment by ashfaq92** [comment]
![image](https://user-images.githubusercontent.com/28701122/75604908-8cee6d80-5b18-11ea-8342-ccddc58ecdb1.png)

**Comment by jeremy0519** [comment]
You can raise a pr resolving the english part first.

**Comment by zhaofeng-shu33** [comment]
Maybe we only need Chinese and English. And Chinese is of highest priority.

**Comment by jeremy0519** [comment]
> Maybe we only need Chinese and English. And Chinese is of highest priority.

Chinese is already ready.

**Comment by ashfaq92** [comment]
> You can raise a pr resolving the english part first.

english part is done. my friend is working on french

**Comment by ashfaq92** [comment]
somebody proof read my english translation

**Comment by jeremy0519** [comment]
Have you raised a pr?

**Comment by ashfaq92** [comment]
i am new to this. I have just shared english translated word file above.

**Comment by ashfaq92** [comment]
somebody else can create pr with english translation. I have translated all survey questions in english

**Comment by zhaofeng-shu33** [comment]
@ashfaq92 You can create a file called "need-questionnaire.md" in `blog/en-us` and create the pull request.

**Comment by jeremy0519** [comment]
@ashfaq92 Have you translated the doc itself? Not the survey.

**Comment by ashfaq92** [comment]
do you mean: have I translated questionnaire by myself? If you mean this, I took help from translate.google.com. That is why, it needs proofreading. Somebody who knows both chinese and english can proof read it. I only know english

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zhaofeng-shu33** [comment]
I think I can translate the draft and let @ashfaq92 do some kind of proof-reading.

**Comment by jeremy0519** [comment]
How can we put the translated survey on the website? It's original link is not on our website.

**Comment by ashfaq92** [comment]
Dear @zhaofeng-shu33, I've reviewed your [translation](https://github.com/wuhan2020/wuhan2020.github.io/pull/346) and given some comments. I suggest using the "Language Tool" chrome extension for minor spelling and grammatical mistakes.  Thank you!

**Comment by jeremy0519** [comment]
> Blog的翻译应该向后放放，优先级更高的应该是docs下的文章
