### ISSUE TITLE
[Translation Support] Wuhan2020 intro

### ISSUE THREAD

**Issue by jeremy0519** [wuhan2020/wuhan2020.github.io#309]
Need to add all language support for the following document:
[blog/zh-cn/wuhan2020-intro.md](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/blog/zh-cn/wuhan2020-intro.md)

- [ ] To English: `blog/en-us/wuhan2020-intro.md`
- [ ] To Japanese: `blog/ja-jp/wuhan2020-intro.md`
- [ ] To Italiana: `blog/it-it/wuhan2020-intro.md`
- [ ] To French: `blog/fr-fr/wuhan2020-intro.md`
- [ ] To Portugues: `blog/pt-br/wuhan2020-intro.md`

**Comment by jeremy0519** [comment]
> Blog的翻译应该向后放放，优先级更高的应该是docs下的文章
