### ISSUE TITLE
[Translation Support] Respected all engineers

### ISSUE THREAD

**Issue by jeremy0519** [wuhan2020/wuhan2020.github.io#310]
Need to add all language support for the following document:
[blog/en-us/respected-all-engineers.md](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/blog/en-us/respected-all-engineers.md)

- [ ] To Chinese: `blog/zh-cn/respected-all-engineers.md`
- [ ] To Japanese: `blog/ja-jp/respected-all-engineers.md`
- [ ] To Italiana: `blog/it-it/respected-all-engineers.md`
- [ ] To French: `blog/fr-fr/respected-all-engineers.md`
- [ ] To Portugues: `blog/pt-br/respected-all-engineers.md`

**Comment by jeremy0519** [comment]
> Blog的翻译应该向后放放，优先级更高的应该是docs下的文章
