### ISSUE TITLE
[doc] Add French Translation

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#69]
This is the epic issues for adding French Translation. If you're a contributor, it would be great if you can open an issue for each of the sub tasks mentioned here.

To be translated (in priority)

Finished
- [x] `docs/fr-fr/dev/mailing-list-guide.md`: Wei XIE
- [x] `docs/fr-fr/dev/information-guide.md`: Contributing @bengbeng233
- [x] `docs/fr-fr/overview`: 
- [x] `docs/fr-fr/dev/dev-env-setup.md`: Contributed by @AnnaCICI 
- [x] `blog/fr-fr/wuhan2020-official-announcement.md`: @沈屹妍Camille from shimo
- [x] `docs/fr-fr/dev/quickstart.md`: Contributed by @AnnaCICI 
- [x] `docs/fr-fr/overview/what-is-wuhan2020.md`: Contributed by @bengbeng233 
- [ ] `docs/fr-fr/dev/contributing.md` Contributed by @AnnaCICI
- [x] `docs/fr-fr/overview/faq.md`: Contributed by @bengbeng233 
- [x] `docs/fr-fr/developers/developers_dev.md`: Contributed by @AnnaCICI 
- [x] `docs/fr-fr/user/website-guides.md`: Contributed by @bengbeng233
- [x] `blog/fr-fr/download.md`: Contributed by @AnnaCICI

**Comment by AnnaCICI** [comment]
Hello @GindaChen,

Ok i will start helping out with the french translation, you can assign this task to me.
I will subsequently create issues for the sub tasks.

**Comment by GindaChen** [comment]
Fantastic! 
See if you would also like to coordinate people in the wechat group and assign tasks for them. Many of them are not git users, so technical helps are needed.

**Comment by AnnaCICI** [comment]
Hello, all sub tasks have been done 

> This is the epic issues for adding French Translation. If you're a contributor, it would be great if you can open an issue for each of the sub tasks mentioned here.
> 
> To be translated (in priority)
> 
> * [ ]  `docs/fr-fr/dev/information-guide.md`: Contributing @bengbeng233
> * [ ]  `docs/fr-fr/overview`:
> * [ ]  `docs/fr-fr/dev/mailing-list-guide.md`: @wei
> 
> Finished
> 
> * [x]  `docs/fr-fr/dev/dev-env-setup.md`: Contributed by @AnnaCICI
> * [x]  `blog/fr-fr/wuhan2020-official-announcement.md`: @沈屹妍Camille from shimo
> * [x]  `docs/fr-fr/dev/quickstart.md`: Contributed by @AnnaCICI
> * [x]  `docs/fr-fr/overview/what-is-wuhan2020.md`: Contributed by @bengbeng233
> * [x]  `docs/fr-fr/dev/contributing.md`
> * [x]  `docs/fr-fr/overview/faq.md`: Contributed by @bengbeng233
> * [x]  `docs/fr-fr/developers/developers_dev.md`: Contributed by @AnnaCICI
> * [x]  `docs/fr-fr/user/website-guides.md`: Contributed by @AnnaCICI
> * [x]  `blog/fr-fr/download.md`: Contributed by @bengbeng233

**Comment by GindaChen** [comment]
Thanks all for your effort! Please check the contributor in this page. If they don't match, comment below and let me know.

**Comment by AnnaCICI** [comment]
> Thanks all for your effort! Please check the contributor in this page. If they don't match, comment below and let me know.

Hello, these are right contributors for page

  docs/fr-fr/dev/contributing.md Contributed by @AnnaCICI
  docs/fr-fr/user/website-guides.md: Contributed by @bengbeng233
  blog/fr-fr/download.md: Contributed by @AnnaCICI
