### ISSUE TITLE
[doc] Revise Japanese Translation

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#74]
This is the epic issues for adding Italian Translation. If you're a contributor, it would be great if you can open an issue for each of the sub tasks mentioned here.

@RRFHOUDEN It would be awesome if you can help _coordinate_ the translation of these documentations to Japanese. Feel free to distribute the tasks to other people in Slack with Japanese specialty, but call out the work below in comment so that we don't have duplicate works.

Ready for review:
- [x] [Index](https://community.wuhan2020.org.cn/ja-jp/index.html) Contributor @RRFHOUDEN
- [x] [What is Wuhan2020](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/docs/ja-jp/overview/what-is-wuhan2020.md) Contributor @GindaChen @RRFHOUDEN
- [x] [Official Announcement](https://community.wuhan2020.org.cn/ja-jp/docs/dev/quickstart.html) Contributor @GindaChen @RRFHOUDEN

Not translated yet:
- [x] [FAQ](https://community.wuhan2020.org.cn/en-us/docs/overview/faq.html): Contributor @RRFHOUDEN
- [x] [Data Collection Guide](https://community.wuhan2020.org.cn/en-us/docs/dev/information-guide.html): Contributor @Pandar1Young
- [x] [Guide for contributor](https://community.wuhan2020.org.cn/en-us/docs/dev/contributing.html): Contributor @Hee-San 
- [x] [Github Repo Processing](https://community.wuhan2020.org.cn/en-us/docs/dev/dev-env-setup.html):  Contributor @jeremy0519

**Comment by RRFHOUDEN** [comment]
I will review "Index" latter.

**Comment by chenrui333** [comment]
I added the `help wanted` tag to draw more attentions on the issue triage.

**Comment by RRFHOUDEN** [comment]
Sorry to ask such a basic question :(
When I suggest to revise Japanese translation, what should I do?
I'd like to review "index", and I think it has several unnatural expressions.
But, I don't know what to do next

**Comment by GindaChen** [comment]
@RRFHOUDEN Would you like to review this [What is Wuhan2020?](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/docs/ja-jp/overview/what-is-wuhan2020.md)

I post the list of review documents at the top of this issue page.

**Comment by Pandar1Young** [comment]
I can translate 'Data Collection Guide' page

**Comment by GindaChen** [comment]
@Pandar1Young Fantastic! You can raise a PR refering this issue when you finish the translation.

**Comment by Hee-San** [comment]
I would like to translate 'Guide for contributor' page

**Comment by GindaChen** [comment]
Go for it! Here is the [original doc](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/docs/en-us/dev/contributing.md). When you're done translation, raise a PR and put the translation file into `/docs/ja-jp/dev/contributing.md`

**Comment by Pandar1Young** [comment]
> @Pandar1Young Fantastic! You can raise a PR refering this issue when you finish the translation.

Sorry I cant create a new PR from my branch, shown that i dont have the permission to create one.
Could some1 help?

**Comment by jeremy0519** [comment]
I can translate the last one, which is github repo processing

**Comment by jeremy0519** [comment]
@GindaChen I think you can close the issue.

**Comment by GindaChen** [comment]
Fantastic! Thank you all for the contribution!
